coreapp/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('herb/', views.herbview, name='herbview'),
    path('herb/<int:herb_id>/', views.detailherb, name='detailherb'),
    path('compound/', views.compoundview, name='compoundview'),
    path('compound/<int:compound_id>/', views.detailcompound, name='detailcompound'),
    path('target/', views.targetview, name='targetview'),
    path('target/<int:target_id>/', views.detailtarget, name='detailtarget'),
    path('disease/', views.diseaseview, name='diseaseview'),
    path('query/', views.querycansmiles.as_view(), name='querycansmiles')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coreapp.urls')),
]

coreapp/models.py
from django.db import models


# Create your models here.
class Herb(models.Model):
    scientific_name = models.CharField(max_length=50, unique=True)
    vietnamese_name = models.CharField(max_length=50, unique=True)
    familia = models.CharField(max_length=50, null=True)
    vietnamese_synonyms = models.CharField(max_length=150, null=True)
    stem = models.CharField(max_length=300, null=True)
    root = models.CharField(max_length=300, null=True)
    leaf = models.CharField(max_length=300, null=True)
    flower = models.CharField(max_length=400, null=True)
    fruit = models.CharField(max_length=200, null=True)
    image0 = models.CharField(max_length=200, null=True)
    image1 = models.CharField(max_length=200, null=True)
    image2 = models.CharField(max_length=200, null=True)
    image3 = models.CharField(max_length=200, null=True)
    image_ref = models.CharField(max_length=200, null=True)
    time = models.DateField(null=True)
    def __str__(self):
        return '%s' % (self.vietnamese_synonyms)


class Compound(models.Model):
    iupac_name = models.CharField(max_length=400)
    synonym = models.CharField(max_length=100, unique=True)
    formula = models.CharField(max_length=200, null=True)
    structure = models.CharField(max_length=200, null=True)
    pubchem_ref = models.CharField(max_length=150, null=True)
    can_smiles = models.CharField(max_length=250, null=True)
    iso_smiles = models.CharField(max_length=250, null=True)
    herb = models.ManyToManyField(Herb)


class Target(models.Model):
    protein_name = models.CharField(max_length=100, unique=True)
    gene_name = models.CharField(max_length=100)
    uniprot_ref = models.CharField(max_length=100, null=True)
    uniprot_code = models.CharField(max_length=50, null=True)
    herb = models.ManyToManyField(Herb)
    compound = models.ManyToManyField(Compound)

class Disease(models.Model):
    disease_name_en = models.CharField(max_length=100, unique=True)
    icd10_ref_en = models.CharField(max_length=200)
    icd10_code_en = models.CharField(max_length=50)
    disease_name_vn = models.CharField(max_length=100)
    icd10_ref_vn = models.CharField(max_length=200)
    icd10_code_vn = models.CharField(max_length=50)

coreapp/forms.py
from django import forms

class QuerySmiles(forms.Form):
    smiles_str = forms.CharField(max_length=300, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'smiles-input'}))
    thresh_hold = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'radio-inline', 'checked': ''}),
                                    choices=[('0.7', '0.7'), ('0.5', '0.5'), ('0.3', '0.3')])

coreapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Herb, Compound, Target, Disease
import numpy as np
from rdkit import Chem
from rdkit.Chem import Descriptors
from rdkit import DataStructs
from .func import smiles_encoder, smiles_decoder
from django.views import View
from .forms import QuerySmiles
import json
# Create your views here.


def index(request):
    context = {'name': [1, 2, 3, 4]}
    mat = smiles_encoder('c1nccc2n1ccc2')
    print(mat.shape)
    print(type(mat))
    return render(request, 'coreapp/index.html')


def herbview(request):
    list_herb = Herb.objects.all()
    context = {'name': list_herb}
    return render(request, 'coreapp/herb.html', context)


def detailherb(request, herb_id):
    h = Herb.objects.get(pk=herb_id)
    context = {'herb': h}
    return render(request, 'coreapp/detail_herb.html', context)


def compoundview(request):
    list_compound = Compound.objects.all()
    list_mwt=[]
    list_logp=[]
    list_tpsa=[]
    list_hacc=[]
    list_hdon=[]
    list_hrot=[]
    for i in range(len(list_compound)):
        mol=Chem.MolFromSmiles(list_compound[i].can_smiles)
        list_mwt.append(round(Descriptors.MolWt(mol),3))
        list_logp.append(round(Descriptors.MolLogP(mol),3))
        list_tpsa.append(round(Descriptors.TPSA(mol),3))
        list_hacc.append(round(Descriptors.NumHAcceptors(mol),3))
        list_hdon.append(round(Descriptors.NumHDonors(mol),3))
        list_hrot.append(round(Descriptors.NumRotatableBonds(mol), 3))

    #list_test = [75, 69, 56, 46, 47, 79, 92, 97, 89, 88, 36, 96, 105, 32, 116, 101, 79, 93, 91, 112]
    #list_test.sort()
    '''list_mwt.sort()
    list_logp.sort()
    list_tpsa.sort()
    list_hacc.sort()'''

    q1 = np.percentile(list_mwt, 25, interpolation='midpoint')
    q2 = np.median(list_mwt)
    q3 = np.percentile(list_mwt, 75, interpolation='midpoint')
    iqr = q3-q1
    high = round(q3 + 1.75*iqr,3)
    low = round(q1 - 1.75*iqr,3)
    box_data = [low,round(q1,3),round(q2,3),round(q3,3),high]

    q1_logp = np.percentile(list_logp, 25, interpolation='midpoint')
    q2_logp = np.median(list_logp)
    q3_logp = np.percentile(list_logp, 75, interpolation='midpoint')
    high_logp = round(q3_logp + 1.75*(q3_logp - q1_logp),3)
    low_logp = round(q1_logp - 1.75*(q3_logp - q1_logp), 3)
    logp_data = [low_logp,round(q1_logp,3),round(q2_logp,3),round(q3_logp,3),high_logp]

    q1_tpsa = np.percentile(list_tpsa, 25, interpolation='midpoint')
    q2_tpsa = np.median(list_tpsa)
    q3_tpsa = np.percentile(list_tpsa, 75, interpolation='midpoint')
    high_tpsa = round(q3_tpsa + 1.75*(q3_tpsa - q1_tpsa),3)
    low_tpsa = round(q1_tpsa - 1.75*(q3_tpsa - q1_tpsa),3)
    tpsa_data = [low_tpsa,round(q1_tpsa,3),round(q2_tpsa,3),round(q3_tpsa,3),high_tpsa]

    q1_hacc = np.percentile(list_hacc, 25, interpolation='midpoint')
    q2_hacc = np.median(list_hacc)
    q3_hacc = np.percentile(list_hacc, 75, interpolation='midpoint')
    high_hacc = round(q3_hacc + 1.75*(q3_hacc - q1_hacc), 3)
    low_hacc = round(q1_hacc - 1.75*(q3_hacc - q1_hacc),3)
    hacc_data = [low_hacc,round(q1_hacc,3),round(q2_hacc,3),round(q3_hacc,3),high_hacc]

    q1_hdon = np.percentile(list_hdon, 25, interpolation='midpoint')
    q2_hdon = np.median(list_hdon)
    q3_hdon = np.percentile(list_hdon, 75, interpolation='midpoint')
    high_hdon = round(q3_hdon + 1.75 * (q3_hdon - q1_hdon), 3)
    low_hdon = round(q1_hdon - 1.75 * (q3_hdon - q1_hdon), 3)
    hdon_data = [low_hdon, round(q1_hdon, 3), round(q2_hdon, 3), round(q3_hdon, 3), high_hdon]

    q1_hrot = np.percentile(list_hrot, 25, interpolation='midpoint')
    q2_hrot = np.median(list_hrot)
    q3_hrot = np.percentile(list_hrot, 75, interpolation='midpoint')
    high_hrot = round(q3_hrot + 1.75 * (q3_hrot - q1_hrot), 3)
    low_hrot = round(q1_hrot - 1.75 * (q3_hrot - q1_hrot), 3)
    hrot_data = [low_hrot, round(q1_hrot, 3), round(q2_hrot, 3), round(q3_hrot, 3), high_hrot]
    print(hacc_data)
    print(hdon_data)
    print(hrot_data)
    context = {'name': list_compound, 'my_data': box_data, 'logp_data': logp_data, 'tpsa_data': tpsa_data, 'hacc_data':
hacc_data, 'hdon_data': hdon_data, 'hrot_data': hrot_data}
    return render(request, 'coreapp/compound.html', context)


def detailcompound(request, compound_id):
    c = Compound.objects.get(pk=compound_id)
    smi_can = Chem.MolFromSmiles(c.can_smiles)
    mwt = round(Descriptors.MolWt(smi_can),3)
    Hacc = Descriptors.NumHAcceptors(smi_can)
    Hdon = Descriptors.NumHDonors(smi_can)
    rot = Descriptors.NumRotatableBonds(smi_can)

    context = {'compound': c, 'Hacc': Hacc, 'Hdon': Hdon, 'mwt': mwt, 'rot': rot}
    print(type(c))
    return render(request, 'coreapp/detail_compound.html', context)


def targetview(request):
    list_target = Target.objects.all()
    context = {'name': list_target}
    return render(request, 'coreapp/target.html', context)


def detailtarget(request, target_id):
    t = Target.objects.get(pk=target_id)
    context = {'target': t}
    return render(request, 'coreapp/detail_target.html', context)


def diseaseview(request):
    list_disease = Disease.objects.all()
    context = {'name': list_disease}
    return render(request, 'coreapp/disease.html', context)


class querycansmiles(View):
    def get(self, request):
        f = QuerySmiles()
        return render(request, 'coreapp/query.html', {'f': f})

    def post(self, request):
        r = QuerySmiles(request.POST)
        if r.is_valid():
            smi_query = r.cleaned_data['smiles_str']
            thr = r.cleaned_data['thresh_hold']
            mol_query = Chem.MolFromSmiles(smi_query)
            list_compound = Compound.objects.filter()
            simi = []
            simi_dict = {}
            for i in range(len(list_compound)):
                moli = Chem.MolFromSmiles(list_compound[i].can_smiles)
                simii = DataStructs.FingerprintSimilarity(Chem.RDKFingerprint(mol_query), Chem.RDKFingerprint(moli))
                simi_dict[list_compound[i].synonym] = round(simii, 4)
                simi.append(round(simii, 4))
            simi.sort()
            for re in simi_dict:
                if simi_dict[re] >= float(thr):
                    print(re, ': ', simi_dict[re])
            # print(simi)
            print(simi_dict)
            print(smi_query)
            print(thr)
            return render(request, 'coreapp/result.html',{})
        else:
            return HttpResponse('not valid')

coreapp/templates/coreapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}{% endblock %}
    {% block specified %}{% endblock %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <script type="text/javascript" src="http://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'coreapp/style.css' %}" type="text/css">
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" style="background-color: #006400;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="http://localhost/vhm_site/">
        <img src="https://upload.wikimedia.org/wikipedia/vi/c/cd/Logo-hcmut.svg" width="80" height="80">
      </a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="{% url 'index' %}" style="color: White;">Home</a></li>
      <li><a href="{% url 'herbview' %}" style="color: White;">Herb</a></li>
      <li><a href="{% url 'compoundview' %}" style="color: White;">Compound</a></li>
      <li><a href="{% url 'diseaseview' %}" style="color: White;">Disease</a></li>
      <li><a href="{% url 'targetview' %}" style="color: White;">Target</a></li>
        <li><a href="{% url 'querycansmiles' %}" style="color: White;">Search</a></li>
    </ul>
  </div>
</nav>
{% block content0 %}
{% endblock %}
<script type="text/javascript">
$(document).ready(function(){
	$('.myInput').hide();
});
$(document).ready(function(){
    $('table.display').DataTable();
});
</script>
</body>
</html>

coreapp/templates/coreapp/detail_compound.html
{% extends 'coreapp/base.html' %}
{% block title %} <title>{{ compound.synonym }}</title> {% endblock %}
{% block content0 %}
<div class="container" style="padding-top: 100px;">
    <div class="row">
        <div class="col-lg-2" style="background-color:lavender;">abc
        </div>
        <div class="col-lg-1" style="background-color:lavender;">
        </div>
        <div class="col-lg-9" style="background-color:SeaGreen;">
            <p class="head"><strong>Identifers</strong></p>
            <div class="thumbnail">
                <p><strong>Molecular Formula: </strong>{{ compound.formula|safe }}</p>
                <p><strong>IUPAC Name: </strong>{{ compound.iupac_name }}</p>
                <p><strong>Canonical SMILES: </strong>{{ compound.can_smiles }}</p>
            </div>
            
            <p class="head"><strong>2D Structure</strong></p>
                <img src="{{ compound.structure }}" alt="{{ compound.synonym }}" style="width:250px;height:250px;">

            <p class="head"><strong>Computed Properties</strong></p>
            <div class="thumbnail">
                <p><strong>Molecular Weight: </strong>{{ mwt }}</p>
                <p><strong>Hydrogen Bond Acceptor Count: </strong>{{ Hacc }}</p>
                <p><strong>Hydrogen Bond Donor Count: </strong>{{ Hdon }}</p>
                <p><strong>Rotatable Bond Count: </strong>{{ rot }}</p>
            </div>

            <p class="head"><strong>Reference</strong></p>
            <div class="thumbnail">
                <a href="{{ compound.pubchem_ref }}">PubChem (<span id="cid"></span>)</a>
            </div>

            <p class="head"><strong>Related Herbs</strong></p>
            <div class="thumbnail">
                <table class="display compact cell-border">
                <thead>
                <th style="text-align: center;color: #777; font-weight: bold; width: 5%;">ID</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 50%;">Scientific Name</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 25%;">Familia</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 20%;">Image</th>
                </thead>
                <tbody>
                {% if compound %}
                {% for item in compound.herb.all %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td><a href="{% url 'detailherb' item.id %}">{{ item.scientific_name }}</a></td>
                    <td>{{ item.familia }}</td>
                    <td><img src="{{ item.image0 }}" style="width: 170px; height: 200px; display: inline-block;"></td>
                </tr>
                {% endfor %}
                {% endif %}
                </tbody>
                </table>
            </div>

            <p class="head"><strong>Related Targets</strong></p>
            <div class="thumbnail">
                <table class="display compact cell-border">
                <thead>
                <th style="text-align: center;color: #777; font-weight: bold; width: 5%;">ID</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 65%;">Protein Name</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 15%;">Gene Name</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 15%;">UniProt Code</th>
                </thead>
                <tbody>
                {% if compound %}
                {% for item in compound.target_set.all %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td><a href="{% url 'detailtarget' item.id %}">{{ item.protein_name }}</a></td>
                    <td>{{ item.gene_name }}</td>
                    <td>{{ item.uniprot_code }}</td>
                </tr>
                {% endfor %}
                {% endif %}
                </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div id="compound_result" style="display: none;">{{ compound.pubchem_ref }}</div>
<script type="text/javascript">
var ref = document.getElementById("compound_result").textContent;
var cid = ref.slice(42);
document.getElementById("cid").innerHTML = cid;
</script>
{% endblock %}

coreapp/templates/coreapp/detail_herb.html
{% extends 'coreapp/base.html' %}
{% block title %} <title>{{ herb.scientific_name }}</title> {% endblock %}
{% block content0 %}
<div class="container" style="padding-top: 100px;">
    <div class="row">
        <div class="col-lg-2" style="background-color:lavender;">abc
        </div>
        <div class="col-lg-1" style="background-color:lavender;">
        </div>
        <div class="col-lg-9" style="background-color:SeaGreen;">
            <p class="head"><strong>Identifers</strong></p>
            <div class="thumbnail">
                <p><strong>Scientific Name: </strong>{{ herb.scientific_name }}</p>
			   	<p><strong>Familia: </strong>{{ herb.familia }}</p>
			   	<p><strong>Vietnamese Name: </strong>{{ herb.vietnamese_name }}</p>
			   	<p><strong>Vietnamese Synonyms: </strong>{{ herb.vietnamese_synonyms }}</p>
            </div>

            <p class="head"><strong>Images</strong></p>
            <div class="thumbnail">
                <div>
   				<img class="herb_image" src="{{ herb.image0 }}">
   				<img class="herb_image" src="{{ herb.image1 }}" >
   				<img class="herb_image" src="{{ herb.image2 }}" >
   				<img class="herb_image" src="{{ herb.image3 }}" >
   		        </div>
                Reference: GBIF Backbone Taxonomy. Images accessed at
                <a href="{{ herb.image_ref }}" target="_blank">{{ herb.image_ref }}</a> on
                {{ herb.time }}
            </div>

            <p class="head"><strong>Morphology</strong></p>
            <div class="thumbnail">
                <p></p><strong>Thân: </strong>{{herb.stem}}</p>
                <p></p><strong>Rễ: </strong>{{herb.root}}</p>
                <p></p><strong>Lá: </strong>{{herb.leaf}}</p>
                <p></p><strong>Hoa: </strong>{{herb.flower}}</p>
                <p></p><strong>Quả: </strong>{{herb.fruit}}</p>
            </div>

            <p class="head"><strong>Related Compounds</strong></p>
            <div class="thumbnail">
                <table class="display compact cell-border">
                <thead>
                <th style="text-align: center;color: #777; font-weight: bold; width: 5%;">ID</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 50%;">IUPAC Name</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 20%;">Synonym</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 25%;">Structure</th>
                </thead>
                <tbody>
                {% if herb %}
                {% for item in herb.compound_set.all %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td><a href="{% url 'detailcompound' item.id %}">{{ item.iupac_name|safe }}</a></td>
                    <td>{{ item.synonym }}</td>
                    <td><img src="{{ item.structure }}" style="width: 200px; height: 200px; display: inline-block;"></td>
                </tr>
                {% endfor %}
                {% endif %}
                </tbody>
                </table>
            </div>

            <p class="head"><strong>Related Targets</strong></p>
            <div class="thumbnail">
                <table class="display compact cell-border">
                <thead>
                <th style="text-align: center;color: #777; font-weight: bold; width: 5%;">ID</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 65%;">Protein Name</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 15%;">Gene Name</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 15%;">UniProt Code</th>
                </thead>
                <tbody>
                {% if herb %}
                {% for item in herb.target_set.all %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td><a href="{% url 'detailtarget' item.id %}">{{ item.protein_name }}</a></td>
                    <td>{{ item.gene_name }}</td>
                    <td>{{ item.uniprot_code }}</td>
                </tr>
                {% endfor %}
                {% endif %}
                </tbody>
                </table>
            </div>
        </div>
    </div>
{% if herb %}
<ul>
{% for item in herb.compound_set.all %}
<li>{{ item.synonym }}</li>
{% endfor %}
</ul>
{% endif %}
</div>
{% endblock %}

coreapp/templates/coreapp/detail_target.html
{% extends 'coreapp/base.html' %}
{% block title %} <title>{{ target.protein_name }}</title> {% endblock %}
{% block content0 %}
<div class="container" style="padding-top: 100px;">
    <div class="row">
        <div class="col-lg-2" style="background-color:lavender;">abc
        </div>
        <div class="col-lg-1" style="background-color:lavender;">
        </div>
        <div class="col-lg-9" style="background-color:SeaGreen;">
            <p class="head"><strong>Identifers</strong></p>
            <div class="thumbnail">
                <p><strong>Protein Name: </strong>{{ target.protein_name }}</p>
                <p><strong>Gene Name: </strong>{{ target.gene_name }}</p>
                <p><strong>UniProt Code: </strong>{{ target.uniprot_code }}</p>
            </div>

            <p class="head"><strong>Reference</strong></p>
            <div class="thumbnail">
                <a href="{{ target.uniprot_ref }}">UniProt ({{ target.uniprot_code }})</a>
            </div>

            <p class="head"><strong>Related Herbs</strong></p>
            <div class="thumbnail">
                <table class="display compact cell-border">
                <thead>
                <th style="text-align: center;color: #777; font-weight: bold; width: 5%;">ID</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 45%;">Scientific Name</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 25%;">Familia</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 25%;">Image</th>
                </thead>
                <tbody>
                {% if target %}
                {% for item in target.herb.all %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td><a href="{% url 'detailherb' item.id %}">{{ item.scientific_name }}</a></td>
                    <td>{{ item.familia }}</td>
                    <td><img src="{{ item.image0 }}" style="width: 170px; height: 200px; display: inline-block;"></td>
                </tr>
                {% endfor %}
                {% endif %}
                </tbody>
                </table>
            </div>

            <p class="head"><strong>Related Compounds</strong></p>
            <div class="thumbnail">
                <table class="display compact cell-border">
                <thead>
                <th style="text-align: center;color: #777; font-weight: bold; width: 5%;">ID</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 50%;">IUPAC Name</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 20%;">Synonym</th>
                <th style="text-align: center;color: #777; font-weight: bold; width: 25%;">Structure</th>
                </thead>
                <tbody>
                {% if target %}
                {% for item in target.compound.all %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td><a href="{% url 'detailcompound' item.id %}">{{ item.iupac_name|safe }}</a></td>
                    <td>{{ item.synonym }}</td>
                    <td><img src="{{ item.structure }}" style="width: 200px; height: 200px; display: inline-block;"></td>
                </tr>
                {% endfor %}
                {% endif %}
                </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div id="compound_result" style="display: none;">{{ compound.pubchem_ref }}</div>
<script type="text/javascript">
var ref = document.getElementById("compound_result").textContent;
var cid = ref.slice(42);
document.getElementById("cid").innerHTML = cid;
</script>
{% endblock %}

coreapp/templates/coreapp/disease.html
{% extends 'coreapp/base.html' %}
{% block title %} <title>Diseases</title> {% endblock %}
{% block content0 %}
<div class="container" style="padding-top: 100px;">
<table class="display compact cell-border">
    <thead>
        <th style="text-align: center;color: #777; font-weight: bold; width: 3%;">ID</th>
        <th style="text-align: center;color: #777; font-weight: bold; width: 50%;">Disease Name</th>
        <th style="text-align: center;color: #777; font-weight: bold; width: 50%;">ICD-10 Version:2019</th>
    </thead>
    <tbody>
    </tbody>
</table>
</div>
{% endblock %}

coreapp/templates/coreapp/herb.html
{% extends 'coreapp/base.html' %}
{% block title %} <title>Herbs</title> {% endblock %}
{% block content0 %}
<div class="container" style="padding-top: 100px;">
<table class="display compact cell-border">
    <thead>
        <th style="text-align: center;color: #777; font-weight: bold; width: 3%;">ID</th>
		<th style="text-align: center;color: #777; font-weight: bold; width: 15%;">Scientific Name</th>
		<th style="text-align: center;color: #777; font-weight: bold; width: 10%;">Familia</th>
		<th style="text-align: center;color: #777; font-weight: bold; width: 15%;">Vietnamese Name</th>
		<th style="text-align: center;color: #777; font-weight: bold; width: 42%;">Vietnamese Synonyms</th>
		<th style="text-align: center;color: #777; font-weight: bold; width: 15%;">Image</th>
    </thead>
    <tbody>
        {% for item in name %}
        <tr>
            <td>{{ item.id }}</td>
            <td><a href="{% url 'detailherb' item.id %}">{{ item.scientific_name }}</a></td>
            <td>{{item.familia}}</td>
            <td>{{ item.vietnamese_name }}</td>
            <td>{{item.vietnamese_synonyms}}</td>
            <td><img src='{{item.image0}}' style='width: 170px; height: 200px; display: inline-block;'></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
<div id="test" class="thumbnail">
    {{array}}
</div>
{% endblock %}

coreapp/templates/coreapp/index.html
{% extends 'coreapp/base.html' %}
{% block title %} <title>Home</title> {% endblock %}

coreapp/templates/coreapp/query.html
{% extends 'coreapp/base.html' %}
{% block title %} <title>Search</title> {% endblock %}
{% block specified %}
<script type="text/javascript" language="javascript" src="https://peter-ertl.com/jsme/JSME_2017-02-26/jsme/jsme.nocache.js"></script>
<script>
    //this function will be called after the JavaScriptApplet code has been loaded.
    function jsmeOnLoad() {
        jsmeApplet = new JSApplet.JSME("jsme_container", "380px", "340px");
   }
</script>
{% endblock %}
{% block content0 %}
<div class="container" style="padding-top: 100px;">
    <div class="thumbnail" style="width: 390px">
    <div id="jsme_container"></div>
    <form action="{% url 'querycansmiles' %}" method="POST" name="form">
        {% csrf_token %}
        <p><input type="button" value="Get SMILES" onclick="getSmiles()"></p>
        <p>{{ f.smiles_str }}</p>
        {% for radio in f.thresh_hold %}
        {{ radio }}
        {% endfor %}
        <p><input type="submit" value="Search"></p>
    </form>
    </div>
</div>
<script>
function getSmiles() {
    var drawing = jsmeApplet.smiles();
    document.form.smiles_str.value = drawing;
}
</script>
{% endblock %}

coreapp/templates/coreapp/target.html
{% extends 'coreapp/base.html' %}
{% block title %} <title>Targets</title> {% endblock %}
{% block content0 %}
<div class="container" style="padding-top: 100px;">
<table class="display compact cell-border">
    <thead>
        <th style="text-align: center;color: #777; font-weight: bold; width: 5%;">ID</th>
		<th style="text-align: center;color: #777; font-weight: bold; width: 50%;">Protein Name</th>
		<th style="text-align: center;color: #777; font-weight: bold; width: 25%;">Gene Name</th>
		<th style="text-align: center;color: #777; font-weight: bold; width: 20%;">Uniprot Code</th>
    </thead>
    <tbody>
        {% for item in name %}
        <tr>
            <td>{{ item.id }}</td>
            <td><a href="{% url 'detailtarget' item.id %}">{{ item.protein_name }}</a></td>
            <td>{{item.gene_name}}</td>
            <td>{{ item.uniprot_code }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}